services:
  backup_service:
    build: .
    image: postgres_azure_backup
    container_name: postgres_azure_backup
    env_file:
      - .env
    environment:
      DATABASE_HOST: ${DATABASE_HOST:-localhost}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
    network_mode: "host"
    restart: no
